name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    env:
      MSYS2_ARCH: i686
    steps:
    - uses: actions/checkout@v1
    - uses: numworks/setup-msys2@v1
      with:
        update: true
        msystem: MINGW32
        
    - name: Install MSYS2 Dependencies
      run:  msys2do pacman --noconfirm -S --needed mingw-w64-i686-gcc make
    - name: make clean
      run:  make -f makefile.mingw32 -j clean
    - name: make
      run:  make -f makefile.mingw32 -j     
